"""base model

Revision ID: 0148e3cffc6b
Revises: 44dc86925812
Create Date: 2021-10-13 19:33:14.928464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0148e3cffc6b'
down_revision = '44dc86925812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sku', sa.String(length=50), nullable=True))
    op.drop_index('suk', table_name='product')
    op.create_unique_constraint(None, 'product', ['sku'])
    op.drop_column('product', 'suk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('suk', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'product', type_='unique')
    op.create_index('suk', 'product', ['suk'], unique=False)
    op.drop_column('product', 'sku')
    # ### end Alembic commands ###
