"""base model

Revision ID: 44dc86925812
Revises: f801afa89602
Create Date: 2021-10-13 19:28:44.866536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44dc86925812'
down_revision = 'f801afa89602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['name'])
    op.add_column('product', sa.Column('suk', sa.String(length=50), nullable=True))
    op.drop_index('SKU', table_name='product')
    op.create_unique_constraint(None, 'product', ['suk'])
    op.drop_column('product', 'SKU')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('SKU', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'product', type_='unique')
    op.create_index('SKU', 'product', ['SKU'], unique=False)
    op.drop_column('product', 'suk')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
