"""base model

Revision ID: f801afa89602
Revises: 207868aeaaf2
Create Date: 2021-10-13 18:51:20.694904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f801afa89602'
down_revision = '207868aeaaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('category', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product_meta', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product_meta', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_meta', 'updated_at')
    op.drop_column('product_meta', 'created_at')
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    op.drop_column('category', 'updated_at')
    op.drop_column('category', 'created_at')
    # ### end Alembic commands ###
