"""base model

Revision ID: fc56ead196cf
Revises: 0148e3cffc6b
Create Date: 2021-10-14 15:24:50.133319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc56ead196cf'
down_revision = '0148e3cffc6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_meta', sa.Column('meta_key', sa.String(length=50), nullable=True))
    op.add_column('product_meta', sa.Column('meta_value', sa.String(length=100), nullable=True))
    op.drop_column('product_meta', 'small_image_url')
    op.drop_column('product_meta', 'large_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_meta', sa.Column('large_image_url', mysql.TEXT(), nullable=True))
    op.add_column('product_meta', sa.Column('small_image_url', mysql.TEXT(), nullable=True))
    op.drop_column('product_meta', 'meta_value')
    op.drop_column('product_meta', 'meta_key')
    # ### end Alembic commands ###
